# ---------------------------------------------------------------------------
# Datadog AWS Integration
#
# How the trust works:
#   Datadog's account (464622532012) assumes a role in YOUR account.
#   The external_id is a secret generated by Datadog that prevents
#   "confused deputy" attacks — without it, anyone who knew the role ARN
#   could assume it by pretending to be Datadog.
#
# Why dd_role_name is a local:
#   datadog_integration_aws_account needs the role name to register the
#   integration. aws_iam_role needs the external_id from
#   datadog_integration_aws_account for the trust policy. If both reference
#   each other's resource, Terraform reports a cycle. Using a local breaks
#   the dependency — both resources read from the local instead of each other.
# ---------------------------------------------------------------------------

locals {
  dd_role_name = "${local.name_prefix}-datadog-integration"
}

data "aws_iam_policy_document" "datadog_assume_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::464622532012:root"] # Datadog's own AWS account
    }

    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [datadog_integration_aws_account.main.auth_config.aws_auth_config_role.external_id]
    }
  }
}

# ---------------------------------------------------------------------------
# IAM permissions
#
# Datadog publishes the exact list of permissions it needs as a Terraform
# data source. Using this instead of hardcoding means you automatically get
# any new permissions Datadog requires as they add features — just re-apply.
#
# Why multiple policies?
# IAM policy documents have a 6144-character size limit. Datadog needs enough
# actions that a single document would exceed that. The chunking logic below
# bins them into ~5900-char groups so each stays under the limit.
# This is boilerplate from Datadog's own template — don't worry about it.
# ---------------------------------------------------------------------------

data "datadog_integration_aws_iam_permissions" "main" {}

locals {
  _dd_perms     = data.datadog_integration_aws_iam_permissions.main.iam_permissions
  _perm_sizes   = [for p in local._dd_perms : length(p) + 3]
  _cumulative   = [for i in range(length(local._perm_sizes)) : sum(slice(local._perm_sizes, 0, i + 1))]
  _chunk_assign = [for c in local._cumulative : floor(c / 5900)]
  dd_chunks     = distinct(local._chunk_assign)
  dd_perm_chunks = [
    for n in local.dd_chunks : [
      for i, p in local._dd_perms : p if local._chunk_assign[i] == n
    ]
  ]
}

data "aws_iam_policy_document" "datadog_permissions" {
  count = length(local.dd_perm_chunks)
  statement {
    actions   = local.dd_perm_chunks[count.index]
    resources = ["*"]
  }
}

resource "aws_iam_policy" "datadog" {
  count  = length(local.dd_perm_chunks)
  name   = "${local.name_prefix}-datadog-integration-${count.index + 1}"
  policy = data.aws_iam_policy_document.datadog_permissions[count.index].json
  tags   = local.common_tags
}

resource "aws_iam_role" "datadog" {
  name               = local.dd_role_name
  description        = "Role assumed by Datadog for AWS integration"
  assume_role_policy = data.aws_iam_policy_document.datadog_assume_role.json
  tags               = local.common_tags
}

resource "aws_iam_role_policy_attachment" "datadog" {
  count      = length(local.dd_perm_chunks)
  role       = aws_iam_role.datadog.name
  policy_arn = aws_iam_policy.datadog[count.index].arn
}

# SecurityAudit is an AWS-managed policy Datadog uses for CSPM and resource discovery.
# Attaching it separately keeps our custom policy focused on metrics/logs/traces.
resource "aws_iam_role_policy_attachment" "datadog_security_audit" {
  role       = aws_iam_role.datadog.name
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}

# ---------------------------------------------------------------------------
# Datadog-side integration resource
#
# This is the Datadog provider resource — it configures what Datadog pulls
# from AWS. Notable decisions vs. the template:
#
#   include_only us-east-1     — all your resources are here; scanning every
#                                region wastes scrape time and adds noise.
#
#   cspm = false               — Cloud Security Posture Management is a
#                                compliance product. Overkill for a portfolio
#                                project and generates a lot of findings noise.
#
#   sources = elbv2+cloudfront — matches what we enabled in the Forwarder.
#                                The Forwarder handles delivery; this tells
#                                the integration which sources to expect.
#
#   No traces_config/xray     — NoteFlow uses Datadog APM, not X-Ray.
# ---------------------------------------------------------------------------

resource "datadog_integration_aws_account" "main" {
  aws_account_id = "659775407889"
  aws_partition  = "aws"
  account_tags   = []

  aws_regions {
    include_only = ["us-east-1"]
  }

  auth_config {
    aws_auth_config_role {
      role_name = local.dd_role_name
    }
  }

  resources_config {
    extended_collection                          = true
    cloud_security_posture_management_collection = false
  }

  logs_config {
    lambda_forwarder {
      lambdas = [module.datadog_forwarder.datadog_forwarder_arn]
      sources = ["elbv2", "cloudfront"]
    }
  }

  traces_config {
    xray_services {}
  }

  metrics_config {
    namespace_filters {}
  }
}

# ---------------------------------------------------------------------------
# Datadog Log Forwarder Lambda
#
# A Lambda function deployed into your account that reads CloudWatch log
# groups and ships them to Datadog. The autosubscription you configured
# in the UI sets up the CloudWatch triggers automatically.
#
# dd_api_key and dd_site reference existing vars — no new secrets needed.
# tags uses merge() to combine project tags with the module's own tag.
# ---------------------------------------------------------------------------

module "datadog_forwarder" {
  source  = "DataDog/log-lambda-forwarder-datadog/aws"
  version = "~> 1.0"

  dd_api_key = var.dd_api_key
  dd_site    = var.dd_site

  tags = merge(local.common_tags, { Terraform = "true" })
}
