aws_region   = "us-east-1"
aws_profile  = "rodrigo-falcao-sandbox"
dd_site      = "datadoghq.com"
github_repo  = "rodfalcon/music-theory-api"
# dd_api_key       = "set via TF_VAR_dd_api_key — never commit"
# db_password      = "set via TF_VAR_db_password — never commit"
# datadog_password = "set via TF_VAR_datadog_password — never commit"
