apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: music-theory
spec:
  selector:
    app: music-theory-api
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP   # internal only — frontend nginx proxies to it
