apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: music-theory
spec:
  selector:
    app: music-theory-ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer   # exposes the app externally
